# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/sm4375-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),sm4375-common)

endif
